### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by tunz** [tunz/binch#1]
Currently, it uses NASM to assemble a code.
But, NASM does not support ARM. So, we need to find an another assembler for ARM.

**Comment by aquynh** [comment]
**llvm-mc** from LLVM has assemblers for multiple archs (X86, Arm, Arm64, Mips, PPC, Sparc, etc), and its Arm support is awesome, so check it out.

btw, we have linked to your project from our website: http://capstone-engine.org/showcase.html

nice tool, keep it up!

**Comment by tunz** [comment]
Thanks!
I'll check it out.
