### ISSUE TITLE
Handling "dword ptr"

### ISSUE THREAD

**Issue by hellman** [tunz/binch#4]
Currently disassembler shows instructions like:

  mov       rsi, qword ptr [rdi]

But the assembler does not accept "ptr" keyword, it wants:

  mov       rsi, qword [rdi]

So it is inconvinient to remove "ptr" by hand.

**Comment by tunz** [comment]
Thanks!

I have a plan to change the default assembler from nasm to llvm-mc, and llvm-mc supports "ptr" keyword.
So, it might be fixed soon, if users change their default assembler.

It might be needed to patch nasm version too, for users who don't want to use llvm-mc.
But, it is confusing to preprocess an assembly code.
I have to remove both 'dword' and 'ptr' for some instructions (e.g. lea), or only 'ptr' for some other instructions (e.g. mov, push)
So, I applied only hotfix for this issue.
