### ISSUE TITLE
ditch llvm-mc?

### ISSUE THREAD

**Issue by aquynh** [tunz/binch#5]
is it a right time to ditch llvm-mc and use Keystone (www.keystone-engine.org) for assembling?
Keystone has a very simple API, so it is easy to plug in binch: http://www.keystone-engine.org/docs/tutorial.html

cheers.

**Comment by tunz** [comment]
Great! I'll try it.

**Comment by tunz** [comment]
BTW, When is your plan to upload the keystone package to pip?

**Comment by aquynh** [comment]
Yes, i will do that for v1.0

**Comment by aquynh** [comment]
FYI, keystone is on PyPi under the name "keystone-engine" now.

so you can install keystone with:

    $ sudo pip install keystone-engine

NOTE that this also downloads & builds the core & everything needed, so you need to have Cmake installed on your machine (as core building needs Cmake).

**Comment by tunz** [comment]
Thanks! now binch uses keystone.
